### ISSUE TITLE
Null icons in Gnome 3.36.1 now show "missing icon" icons

### ISSUE THREAD

**Issue by prurigro** [ubuntu/gnome-shell-extension-appindicator#225]
Tray applets that have rows without an icon previously showed no icon, but as of upgrading from 3.36.0 to 3.36.1, now display an alert icon to signify that an icon couldn't be loaded.

![null-icons](https://user-images.githubusercontent.com/1149238/78172704-85c2c400-7424-11ea-8f83-f8805b7344c7.png)

**Comment by Bicet** [comment]
Same happening here :+1:

**Comment by Razer0123** [comment]
Same

**Comment by grilledcarpet** [comment]
I too can confirm this issue. Spent a period of time thinking something was wrong with my icons before realising the issue was here!

**Comment by koroki** [comment]
It is not an error of the extension, if not a bug of gnome or a politic change (again...), since other extensions have similar problems, such as https://github.com/kgshank/gse-sound-output-device-chooser/issues/95

**Comment by terencode** [comment]
The part where there really shouldn't be any icons shown is now fixed in `gnome-3-36` branch:  https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/51e9f19f2ff5d2863a23f762223596de419fc00c

**Comment by BjoernDaase** [comment]
I think this can be closed here because the bug was clearly on the gnome-shell side which is already fixed.

**Comment by Tarekrahman5500** [comment]
not fix

**Comment by Sherlock-Holo** [comment]
test is arch gnome 3.36.1-1, not fix

**Comment by terencode** [comment]
Yes because it landed after 3.36.1, so : 
- wait for 3.36.2
- manually compile it with the fix
- if you are on archlinux, you may use https://aur.archlinux.org/packages/gnome-shell-performance/

**Comment by aryklein** [comment]
Same issue here: Arch Linux running Gnome 3.36.1-1

**Comment by fajaryanw** [comment]
now this issue has been fixed with gnome-shell 3.36.2-1 for Arch Linux

**Comment by JerryPenguin** [comment]
Not fixed under Fedora 32 with gnome-shell-3.36.2-2.fc32.x86_64

**Comment by enigma131** [comment]
Still not fixed under Fedora 32 with gnome-shell-3.36.5-1.fc32.x86_64 . Tested with radiotray-ng from repo, can't use application because it is based on tray-icon commands.

**Comment by enigma131** [comment]
Fixed by installing top icon plus gnome shell extension

**Comment by ChuckNorrison** [comment]
no icons after some months on ubuntu 20.04. Just tried to disable/enable Gnome Extensions in ubuntu Tweaks settings without success.

Iam using gnome shell in version 3.36.4. Remmina and Dropbox Icons are shown. Gnome Extension icon and i.e. Flameshot are missing since today. Worked with this installation for around 8 month without any issues.
