### ISSUE TITLE
3 dots instead of icon in gnome shell 3.36

### ISSUE THREAD

**Issue by mike2307** [ubuntu/gnome-shell-extension-appindicator#232]
After upgrading to Fedora 32, all legacy tray icons show 3 dots instead of the real icon.

In this case, the 3 dots should represent the nextcloud icon:
![Tray](https://user-images.githubusercontent.com/29705161/80301955-69a60e80-87a7-11ea-8d4a-d0eb52964a2f.png)

The same is the case for other legacy tray icons. In my case those are e.g. steam and electron mail.

The used version is gnome-shell-extension-appindicator.noarch 33-1.fc32

**Comment by emichael** [comment]
I'm having the same issue with Chrome/Hangouts indicators after upgrading to Ubuntu 20.04 from 18.04. Interestingly, after I restart the shell, the three dots and the chrome/hangouts appindicators disappear from the top bar entirely. One time the chrome/hangouts icons actually did appear in the top bar but disappeared after the next restart. There appears to be some sort of race condition in the process that converts legacy icons?

**Comment by Nesaijn** [comment]
It looks like the same problem I have.
#229

**Comment by luizesv** [comment]
The same with me, upgrade from pop_os 19.10 to 20.04 and got that.

**Comment by naz01101011** [comment]
Same here, though the pop-up menu works. On my side, Enpass tray icon works normal, but Teams or Remmina ones appear as three dots. Note that I am not using any tray icon Gnome extension.

**Comment by 3v1n0** [comment]
This should be fixed by gnome-shell 3.36.2, can you confirm?

**Comment by Nesaijn** [comment]
Not for me. I still get these errors when starting ElectronMail and the icon is not shown correctly:

```
Mai 19 10:19:59 zodd-pc gnome-shell[1176]: JS ERROR: Exception in callback for signal: property-changed: GdkPixbuf.PixbufError: Unrecognized image file format
                                           _updateImage@/home/zodd/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:618:49
                                           _onPropertyChanged@/home/zodd/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:554:42
                                           _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                           property_set@/home/zodd/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:125:14
                                           _endRequestProperties/<@/home/zodd/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:271:33
                                           _endRequestProperties@/home/zodd/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/dbusMenu.js:266:19
                                           asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13

```

**Comment by bulletmark** [comment]
I get the same issue reported by @emichael. I am using Arch Linux where `gnome-shell` is version `1:3.36.2+7+ge4199c71c-1`.

**Comment by tflori** [comment]
I'm also having problems with the icons for legacy applications. In my case it was (yes, was - I found a solution) the owncloud icon. The reason for that is not clear to me as I don't know much about the icon theme handling in linux.

My findings: `icon_theme.lookup_icon_for_scale` returns null for the icon returned from the application (owncloud tries to use `state-ok`). That is shown in the system logs as `appindicatorsupport@rgcjonas.gmail.com[76875]: ownCloud, Impossible to lookup icon for 'state-ok'` 
. First I thought it would be enough to refactor the panel specification:

```js
                // indicator-application looks up a special "panel" variant, we just replicate that here
                // try to look up the icon in the icon theme
                iconInfo = icon_theme.lookup_icon_for_scale(name + "-panel", size, scale,
                    Gtk.IconLookupFlags.GENERIC_FALLBACK);

                // no panel icon - lets try the "non-panel" variant
                if (iconInfo === null) {
                    iconInfo = icon_theme.lookup_icon_for_scale(name, size, scale,
                      Gtk.IconLookupFlags.GENERIC_FALLBACK);
                }
```

But that didn't work either. I don't know if it makes sense to look for the original name when the `<icon>-panel` does not exist.

But I found out that it is working when we just return the name as path - maybe it is then be used as relative path.

**Comment by veddox** [comment]
On Ubuntu 20.04, Gnome 3.36.2. Am seeing this issue with the Nextcloud desktop client (a Qt application). Mattermost (an Electron app), works fine. 

The disappearing icons after renewed login that @emichael mentions seem to be a consequence of #228.

**Comment by Nesaijn** [comment]
For ElectronMail the latest updated solved my issue with its tray icon.
https://github.com/vladimiry/ElectronMail/releases/tag/v4.6.0

**Comment by veddox** [comment]
I get the impression we're looking at multiple issues here that all result in the "three-dot icon". My error message is different from the two above and seems to be the consequence of a slow starting Nextcloud client - see my write-up [here](https://github.com/nextcloud/desktop/issues/1977#issuecomment-663062174). I'm not yet sure though whether it's better to fix the issue here or over there.

**Comment by jzazo** [comment]
Keepassxc, which also uses Qt, shows three dots as well. 

For a different [problem](https://github.com/keepassxreboot/keepassxc/issues/3120) they concluded it was a Qt problem. The three dot problem has not been assessed, but Qt may be the culprit in all these cases?

**Comment by veddox** [comment]
> For a different [problem](https://github.com/keepassxreboot/keepassxc/issues/3120) they concluded it was a Qt problem. The three dot problem has not been assessed, but Qt may be the culprit in all these cases?

Well, the thing is, the "three-dot problem" is really only a symptom that can potentially have plenty of very different causes (kind of like a runny nose, really :sneezing_face: :mask: :sweat_smile: )

If you look at the `IconActor` class in `appIndicator.js`, you see the following code:

https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/32f2f34ae382a4af850471a131cf9b5e42231ac5/appIndicator.js#L288-L296

Here you see that appindicator sets a default fallback icon (which on my system is located at `/usr/share/icons/Adwaita/scalable/status/image-loading-symbolic.svg`) - the infamous "three dots". Basically, appindicator initially sets *all* tray icons to the fallback icon, before changing them to whatever the application wants. This only happens when the `ready` signal is received in [line 321](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/32f2f34ae382a4af850471a131cf9b5e42231ac5/appIndicator.js#L321). In short, if there is any error between the first initialisation and the actual setting of the application's systray icon, the symptom is going to be the "three dots".

(If you reread the above thread, you will notice that we do in fact have at least three different error messages we're talking about - one missing icon, one bad file format, and one null pointer exception. Also note that Electron-based apps are having issues too, not only Qt.)

**Comment by cAstraea** [comment]
I'm seeing it too on ubuntu 20.04.... Sorry can't be more useful just switched to Linux still getting used to everything :) Pressing ALT + f2 and r and enter makes it disappear. (I'm thinking this is the equivalent of killing and restarting explorer on windows or finder on mac ? )

**Comment by loulou921222** [comment]
I have the exact same problem with teamviewer, 
![image](https://user-images.githubusercontent.com/39203111/94745362-7a6c3900-0372-11eb-9770-3b7cfc1164af.png)

**Comment by loulou921222** [comment]
```
gnome-shell[973]: JS ERROR: Exception in callback for signal: ready: TypeError: this._indicator.id is null
                                            _updateIconClass@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:386:34
                                            _init/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:364:18
                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                            _checkIfReady@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:118:18
                                            AppIndicators_AppIndicator/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:81:26
```

**Comment by R-033** [comment]
Have this problem with Steam

**Comment by loulou921222** [comment]
> Have this problem with Steam

That's interesting, because steam displays for me fine.

**Comment by cAstraea** [comment]
I found what was the cause for me it was a chrome extension. In google chrome it shows the google tray icon but when using chromium it shows that.

**Comment by loulou921222** [comment]
It doesn't matter if I reload or relogin, it's always 3 dots for teamviewer and others show up fine

**Comment by tflori** [comment]
I see the same: teamviewers indicator has no id. I added a warning message for that:
```
Okt 19 09:00:22 miracle appindicatorsupport@rgcjonas.gmail.com[2679]: Indicator has no id: {"busName":":1.380","_uniqueId":":1.380/StatusNotifierItem","_accumuledSignals":{},"_cancellable":{},"_proxy":{"Category":null,"Id":null,"Title":null,"Status":null,"WindowId":null,"IconThemePath":null,"Menu":null,"ItemIsMenu":null,"IconName":null,"IconPixmap":null,"OverlayIconName":null,"OverlayIconPixmap":null,"AttentionIconName":null,"AttentionIconPixmap":null,"AttentionMovieName":null},"_signalConnections":[{"id":1,"name":"destroy","disconnected":false},{"id":2,"name":"destroy","disconnected":false},{"id":3,"name":"destroy","disconnected":false},{"id":4,"name":"icon","disconnected":false},{"id":5,"name":"destroy","disconnected":false},{"id":6,"name":"overlay-icon","disconnected":false},{"id":7,"name":"destroy","disconnected":false},{"id":8,"name":"reset","disconnected":false},{"id":9,"name":"destroy","disconnected":false},{"id":10,"name":"ready","disconnected":false},{"id":11,"name":"destroy","disconnected":false},{"id":12,"name":"ready","disconnected":false},{"id":13,"name":"destroy","disconnected":false},{"id":14,"name":"menu","disconnected":false},{"id":15,"name":"destroy","disconnected":false},{"id":16,"name":"label","disconnected":false},{"id":17,"name":"destroy","disconnected":false},{"id":18,"name":"status","disconnected":false},{"id":19,"name":"destroy","disconnected":false},{"id":20,"name":"reset","disconnected":false},{"id":21,"name":"destroy","disconnected":false},{"id":22,"name":"destroy","disconnected":false}],"_nextConnectionId":23,"isReady":true,"_proxyPropertyList":[]}
```

**Comment by twbeosl** [comment]
I've had two sets of three dots show up on mine. One of them (the one on the left) will start Google Hangouts if clicked. The other does nothing. Can confirm the issue disappears with the Alt-F2 r fix.

**Comment by vageliskatsiotis** [comment]
> I have the exact same problem with teamviewer,
> ![image](https://user-images.githubusercontent.com/39203111/94745362-7a6c3900-0372-11eb-9770-3b7cfc1164af.png)

Same  here. Only with teamviewer.

Arch, gnome shell 3.38.1, extension 3.38

**Comment by gitrequests** [comment]
Have this problem with KeyPassXC, Google Hangouts from Chromium extension and one more app.
Ubuntu 20.04.1 LTS
GNOME 3.36.3
![Screenshot from 2020-12-01 13-22-03](https://user-images.githubusercontent.com/12627650/100728174-45af4900-33d8-11eb-8a37-3321f5a6e00b.png)

**Comment by rogercreagh** [comment]
A system update today has completely killed the appindicator icons. None of them now show.
Ubuntu now v20.04.1 Gnome 3.36.8

**Comment by emichael** [comment]
I can report the same problem as @rogercreagh. In my case, Slack still shows up fine. The Nextcloud client won't appear at all, even after restarting the shell. Looks like `gnome-shell-extension-appindicator:amd64 (33-1, 33.1-0ubuntu0.20.04.1)` was installed yesterday and might be the culprit.

**Comment by rogercreagh** [comment]
It seems that it might be a timing issue as if I disable the apps run on startup and start them manually once everything has settled down then they appear ok.

PS @emichael how do I downgrade the appindicator?

**Comment by emichael** [comment]
@rogercreagh `apt install gnome-shell-extension-appindicator=33-1` then `apt-mark hold gnome-shell-extension-appindicator` to prevent it from upgrading again next time you run `apt upgrade`.

**Comment by rogercreagh** [comment]
Fabulous, thanks @emichael , that has worked a treat, keypassxc, nextcloud and copyq all now starting on boot and their icons showing again.
Hopefully this is a big that'll get fixed in the next release - does it need a new bug report since this one was originally about the 3 dots appearing which seemed to be cleared by a subsequent update (I had the 3 dots problem with nextcloud on on Ubuntu 20.04 machine but not on an ostensibly identical other one - it then cleared itself after about a month.

**Comment by eneshecan** [comment]
Hi, I am using libappindicator C api for my application and it gives this error:

>Apr 24 22:52:47 ubuntu-dev ubuntu-appindicators@ubuntu.com[1185]: com.github.whatsapp-for-linux.tray, Impossible to lookup icon for 'whatsapp-for-linux-tray-active-panel' in default theme
Apr 24 22:52:48 ubuntu-dev ubuntu-appindicators@ubuntu.com[1185]: unable to update icon for com.github.whatsapp-for-linux.tray
Apr 24 22:52:48 ubuntu-dev ubuntu-appindicators@ubuntu.com[1185]: com.github.whatsapp-for-linux.tray, Impossible to lookup icon for 'whatsapp-for-linux-tray-active-panel' in default theme
Apr 24 22:52:48 ubuntu-dev ubuntu-appindicators@ubuntu.com[1185]: unable to update icon for com.github.whatsapp-for-linux.tray

Event though I am adding custom icons to the default theme as `'whatsapp-for-linux-tray-active` and `'whatsapp-for-linux-tray-attention` and setting the appindicator's icon to those. However, I don't get why the extension is trying to append a `-panel` at the end while searching.

**Comment by 3v1n0** [comment]
@eneshecan I think it may depend on the GIcon you're using...

**Comment by eneshecan** [comment]
> @eneshecan I think it may depend on the GIcon you're using...

What do you mean? Could you please elaborate a bit?

**Comment by caneraydinbey** [comment]
Hello. I have also it. When click, it does not show which it should show
![image](https://user-images.githubusercontent.com/17731063/117582675-dfa7ba00-b10b-11eb-9c67-a20c14b15d51.png)

**Comment by Elmapul** [comment]
same problem here, the problem started a few days after i installed gsconnect , not sure if its related

**Comment by alonsogonzalezleal** [comment]
Same problem here with NordPass on Debian 12, when I install the extension it works perfectly, after reboot the system the 3 dots appears.

**Comment by janvlug** [comment]
I've the impression that for some (but not all) applications (that start automatically when logging in) restarting the application get the icon back. I see the issue with Solaar, Nextcloud, and in the past Element (Riot). It seems that this issue for Element is fixed somehow.

**Comment by tazihad** [comment]
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/283#issuecomment-1943018705

**Comment by RalfJung** [comment]
Following the [instructions](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/355#issuecomment-1214409509), it says that the Id of the icon is `Nextcloud`. The nextcloud image exists in `/usr/share/icons/hicolor/48x48/apps/Nextcloud.png` any many other folders for different resolutions. So it seems like the app is doing everything right and the extension just somehow fails to find the `Nextcloud` icon?

**Comment by RalfJung** [comment]
FWIW for nextcloud it suffices to add a custom icon for Id `Nextcloud`, icon `Nextcloud`. Like, literally use the exact same string as the Id and the icon. Then the icon is fixed. Isn't that what the extension should already be doing automatically? I am quite confused now, is there documentation somewhere on how the icon is determined when there is no custom icon? Clearly it is not using the Id...

**Comment by Klairm** [comment]
I'm having the same problem with MEGASync 
![imagen](https://github.com/ubuntu/gnome-shell-extension-appindicator/assets/40839469/0abec09e-4632-4b6e-af76-624f0e51143c)

Tried restarting the shell but didnt work

**Comment by pewinski** [comment]
Having the same issue for Bitwarden and Signal, but for Signal it's worst: it sometimes renders three dots and sometimes does not show the icon at all (despite having the setting "minimize to system tray" turned ON).

<img width="379" height="31" alt="Image" src="https://github.com/user-attachments/assets/646d9ee7-97e2-45c0-94ce-826aa5822525" />

Restarting these applications does not help, as someone here suggested. 

EDIT: I'm using Ubuntu 26.04 LTS
